# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc
    - exportloopref

linters-settings:
  goimports:
    local-prefixes: github.com/irfndi/goflux

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  gosec:
    excludes:
      - G104  # Audit errors not checked (we handle this case-by-case)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam

    # Exclude test utilities
    - path: testutils\.go
      linters:
        - gosec

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
