# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - unconvert
    - gosec
    - prealloc
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  gosec:
    excludes:
      - G104  # Audit errors not checked (we handle this case-by-case)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec

    # Exclude test utilities
    - path: testutils\.go
      linters:
        - gosec

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true