name = "goflux-telemetry"
main = "src/index.ts"
compatibility_date = "2026-01-01"
account_id = "a37da71c38a2f7ab732057d87d5d0f6e"

[[d1_databases]]
binding = "DB"
database_name = "goflux_telemetry"
database_id = "3c7026bc-3099-434a-a811-90cd404f9585"

# Set TELEMETRY_TOKEN in Cloudflare dashboard Secrets for basic auth
